### ISSUE TITLE
Missing favicon.ico

### ISSUE THREAD

**Issue by Ripollx** [aresta/topotresc#1]
Hi,
I've found your project in the Catalan OSM group. This is amazing.

I've added your data source as base layer for my project, you can see it on: https://ripollx.github.io/osmcatmap2/#map=8/41.69689/1.59647/0&base=5

If it is a problem for you I can remove the layer :)

A small issue in your project is the missing image for favicon.ico, it's not exists on: /docs/images/favicon.ico

Thank you!

**Comment by aresta** [comment]
Yes, I have to add the favicon, I'll do it soon.
Of course you can add the layer in your project, it is very interesting also.  I want to add some of the features in your map like the additional layer, the option to copy the direct link to a position, etc,
Thank you!

**Comment by aresta** [comment]
Favicon (provisional) added.

**Comment by Ripollx** [comment]
Thank you!
